name: seaweed-growth-model
channels:
   - conda-forge
dependencies:
  - python=3.8
  - geoplot
  - pandas=1.4.3
  - setuptools=61.2.0
  - pytest=7.1.2
  - numpy=1.23.1
  - matplotlib=3.5.1
  - geopandas=0.11.1
  - xarray=0.20.1
  - cftime=1.5.1.1
  - scikit-learn=1.1.1
