site_name: Seaweed Growth Model


# Repository
repo_name: Seaweed Growth Model
repo_url: https://github.com/allfed/Seaweed-Growth-Model
edit_uri: ""
# Copyright
copyright: ALLFED

docs_dir: "docs/sources"

plugins:
  - search

theme:
  name: 'readthedocs'
  custom_dir: 'docs'
  palette:
    primary: 'white'
  logo: 'assets/images/logo_full.svg'
  favicon: 'assets/images/favicon.svg'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - instant
nav:
  - Home: index.md
  - modules:
    - src:
      - ocean_section: modules/src/ocean_section.md
      - plotter_lme: modules/src/plotter_lme.md
      - preprocessing: modules/src/preprocessing.md
      - read_files: modules/src/read_files.md
      - seaweed_growth: modules/src/seaweed_growth.md
      - seaweed_model: modules/src/seaweed_model.md
      - write_files: modules/src/write_files.md
