name: docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Autogenerate new documentation
        continue-on-error: true
        run: |
          python automate_mkdocs.py
          git add .
      - name: Update and Build GH Pages
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.2.3
          pip install mkgendocs==0.9.0
          pip install jinja2==2.11
          gendocs --config mkgendocs.yml
      - name: Deploy it to the gh branch
      	run: mkdocs gh-deploy --force --clean --verbose

